# Generated by Django 5.1.15 on 2026-07-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summary",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("running", "running"),
                    ("ready", "ready"),
                    ("failed", "failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
